blog/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', home_view),
    path('blog/', blog_view),
    path('blog/<int:pk>/', blog_detail_view),
    path('about/', about_view),
    path('contact/', contact_view),
    path('category/', category_view),
    path('search/', search_view),
    path('tag/<int:pk>', tag_view)


]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='posts/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, blank=True)

    is_published = models.BooleanField(default=True)

    views = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comments(models.Model):
    name = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField()
    message = models.TextField()

    is_published = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    message = models.TextField()

    is_solved = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Post, Category, Comments, Contact, Tag


def home_view(request):
    categories = Category.objects.all()
    tags = Tag.objects.all()
    posts = Post.objects.filter(is_published=True)
    more_posts = posts.order_by('-views')[:4]
    banner_posts = posts.order_by('-views')[:3]
    latest_posts = posts.order_by('-created_at')[:3]
    data = request.GET
    page = data.get('page', 1)
    page_obj = Paginator(posts, 2)

    context = {
        'tags': tags,
        'more_posts': more_posts,
        'latest_posts': latest_posts,
        'banner_posts': banner_posts,
        'posts': page_obj.get_page(page),
        'categories': categories,
        'home': 'active'
    }

    return render(request, 'index.html', context=context)


def blog_view(request):
    categories = Category.objects.all()
    d = {
        'categories': categories
    }
    return render(request, 'blog.html', context=d)


def about_view(request):
    posts = Post.objects.filter(is_published=True)
    categories = Category.objects.all()
    category = Category.objects.filter().first()
    latest_posts = posts.order_by('-created_at')[:3]
    d = {
        'latest_posts': latest_posts,
        'about': 'active',
        'category': category,
        'categories': categories
    }
    return render(request, 'about.html', context=d)


def category_view(request):
    posts = Post.objects.filter(is_published=True)
    latest_posts = posts.order_by('-created_at')[:3]
    tags = Tag.objects.all()
    categories = Category.objects.all()
    data = request.GET
    cat = data.get('cat', None)
    page = data.get('page', 1)

    if cat:
        cat_name = categories.filter(id=cat).first()
        posts = Post.objects.filter(is_published=True, category_id=cat)
        d = {
            'tags': tags,
            'latest_posts': latest_posts,
            'categories': categories,
            'posts': posts,
            'cat_name': cat_name,
            'category': 'active'
        }
        return render(request, 'category.html', context=d)
    else:
        posts = Post.objects.filter(is_published=True)

    page_obj = Paginator(posts, 2)

    d = {
        'category': 'active',
        'blog': 'active',
        'posts': page_obj.get_page(page),
        'categories': categories
    }
    return render(request, 'category.html', context=d)


def contact_view(request):
    posts = Post.objects.filter(is_published=True)
    latest_posts = posts.order_by('-created_at')[:3]
    categories = Category.objects.all()
    if request.method == 'POST':
        data = request.POST
        obj = Contact.objects.create(name=data['name'],
                                     email=data['email'],
                                     phone=data['phone'],
                                     message=data['message'])
        obj.save()
        return redirect('/contact')
    d = {
        'latest_posts': latest_posts,
        'categories': categories,
        'contact': 'active'
    }
    return render(request, 'contact.html', context=d)


def blog_detail_view(request, pk):
    posts = Post.objects.filter(is_published=True)
    latest_posts = posts.order_by('-created_at')[:3]
    categories = Category.objects.all()
    tags = Tag.objects.filter(id=pk)
    if request.method == 'POST':
        data = request.POST
        comment = Comments.objects.create(post_id=pk, name=data['name'], email=data['email'], message=data['message'])
        comment.save()
        return redirect(f'/blog/{pk}')
    post = Post.objects.filter(id=pk).first()
    post.views += 1
    post.save(update_fields=['views'])
    comments = Comments.objects.filter(post_id=pk)
    context = {
        'latest_posts': latest_posts,
        'tags': tags,
        'post': post,
        'comments': comments,
        'categories': categories,
        'category': 'active'
    }
    return render(request, 'blog-single.html', context=context)


def search_view(request):
    if request.method == 'POST':
        data = request.POST
        query = data['query']
        return redirect(f'/search?q={query}')
    query = request.GET.get('q')
    if query is not None and len(query) >= 1:
        posts = Post.objects.filter(is_published=True, title__icontains=query)
    else:
        posts = Post.objects.filter(is_published=True)
    d = {
        'posts': posts
    }

    return render(request, 'category.html', context=d)

def tag_view(request, pk):
    post = Post.objects.filter(is_published=True)
    more_posts = post.order_by('-views')[:4]
    tags = Tag.objects.all()
    tag = Tag.objects.get(id=pk)
    tag_post = Post.objects.filter(tag=tag)
    d = {
        'more_posts': more_posts,
        'tags': tags,
        'posts': tag_post,
        'tag': tag
    }

    return render(request, 'index.html', context=d)
# def tag_posts_view(request, pk):
#     tag = Tag.objects.all()
#     latest_posts = Post.objects.filter(is_published=True).order_by('-created_at')[:3]
#     categories = Category.objects.all()
#     tag = Tag.objects.get(pk=pk)
#     newest_posts = Post.objects.filter(is_published=True).order_by('-created_at')[:6]
#
#     tag_posts = Post.objects.filter(tags=tag)
#     return render(request, 'index.html', {'tag': tag, 'posts': tag_posts, 'categories': categories, 'tag': tag,
#                                           'latest_posts': latest_posts, 'newest_posts': newest_posts})

templates/about.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

<section class="site-section">
    <div class="container">
        <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="mb-4">Hi There! I'm Meagan Smith</h2>
                        <p class="mb-5"><img src="{% static 'images/img_6.jpg' %}" alt="Image placeholder" class="img-fluid"></p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum minima eveniet recusandae
                            suscipit eum laboriosam fugit amet deleniti iste et. Ad dolores, necessitatibus non saepe
                            tenetur impedit commodi quibusdam natus repellat, exercitationem accusantium perferendis
                            officiis. Laboriosam impedit quia minus pariatur!</p>
                        <p>Dignissimos iste consectetur, nemo magnam nulla suscipit eius quibusdam, quo aperiam quia
                            quae est explicabo nostrum ab aliquid vitae obcaecati tenetur beatae animi fugiat officia id
                            ipsam sint? Obcaecati ea nisi fugit assumenda error totam molestiae saepe fugiat officiis
                            quam?</p>
                        <p>Culpa porro quod doloribus dolore sint. Distinctio facilis ullam voluptas nemo voluptatum
                            saepe repudiandae adipisci officiis, explicabo eaque itaque sed necessitatibus, fuga, ea
                            eius et aliquam dignissimos repellendus impedit pariatur voluptates. Dicta perferendis
                            assumenda, nihil placeat, illum quibusdam. Vel, incidunt?</p>
                        <p>Dolorum blanditiis illum quo quaerat, possimus praesentium perferendis! Quod autem optio
                            nobis, placeat officiis dolorem praesentium odit. Vel, cum, a. Adipisci eligendi eaque
                            laudantium dicta tenetur quod, pariatur sunt sed natus officia fuga accusamus reprehenderit
                            ratione, provident possimus ut voluptatum.</p>
                    </div>
                </div>
<!--                <div class="row mb-5 mt-5">-->
<!--                    <div class="col-md-12 mb-5">-->
<!--                        <h2>My Latest Posts</h2>-->
<!--                    </div>-->
<!--                    <div class="col-md-12">-->
<!--                        {% for post in latest_posts %}-->
<!--                        <div class="post-entry-horzontal">-->
<!--                            <a href="/blog/{{ post.id }}/">-->
<!--                                <div class="image" style="background-image: url({{ post.image.url }});"></div>-->
<!--                                <span class="text">-->
<!--<div class="post-meta">-->
<!--<span class="category">{{ post.category }}</span>-->
<!--<span class="mr-2">{{ post.created_at }}</span> &bullet;-->
<!--<span class="ml-2"><span class="fa fa-comments"></span>{{ comments.count }}</span>-->
<!--</div>-->
<!--<h2>{{ post.title }}</h2>-->
<!--</span>-->
<!--                            </a>-->
<!--                        </div>-->
<!--                        {% endfor %}-->

<!--                    </div>-->
<!--                </div>-->
<!--                <div class="row">-->
<!--                    <div class="col-md-12 text-center">-->
<!--                        <nav aria-label="Page navigation" class="text-center">-->
<!--                            <ul class="pagination">-->
<!--                                <li class="page-item  active"><a class="page-link" href="#">Prev</a></li>-->
<!--                                <li class="page-item"><a class="page-link" href="#">1</a></li>-->
<!--                                <li class="page-item"><a class="page-link" href="#">2</a></li>-->
<!--                                <li class="page-item"><a class="page-link" href="#">3</a></li>-->
<!--                                <li class="page-item"><a class="page-link" href="#">Next</a></li>-->
<!--                            </ul>-->
<!--                        </nav>-->
<!--                    </div>-->
<!--                </div>-->
            </div>

            {% include 'layouts/author_page.html' %}

        </div>
    </div>
</section>

{% endblock %}

templates/blog-single.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

<section class="site-section py-lg">
    <div class="container">
        <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
                <h1 class="mb-4">{{ post.title }}</h1>
                <div class="post-meta">
                    <span class="category">{{ post.category }}</span>
                    <span class="mr-2">{{ post.created_at }}</span> &bullet;
                    <span class="ml-2"><span class="fa fa-comments"></span> {{ comments.count }}</span>
                </div>
                <div class="post-content-body">
                    <p>{{ post.description }}</p>

                    <div class="row mb-5">
                        <div class="col-md-12 mb-4 element-animate">
                            <img src="{{ post.image.url }}" alt="Image placeholder" class="img-fluid">
                        </div>

                    </div>

                </div>
                <div class="pt-5">
                    {% for tag in tags %}
                    <p>Categories: <a href="#">{{ post.category }}</a>, Tags: <a href="/tag/{{ tag.id }}">#{{ tag.name }}</a>, <a
                            href="/tag/{{ tag.id }}"># {{ tag.name }}</a></p>
                    {% endfor %}
                </div>
                <div class="pt-5">
                    <h3 class="mb-5">{{ comments.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in comments %}
                        <li class="comment">

                            <div class="comment-body">
                                <h3>{{ comment.name }}</h3>
                                <div class="meta">{{ comment.created_at }}</div>
                                <p>{{ comment.message }}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method='POST' action="#" class="p-5 bg-light">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input name="name" type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input name="email" type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="message">Message *</label>
                                <textarea name="message" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            {% include 'layouts/author_page.html' %}

        </div>
    </div>
</section>
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="mb-3 ">Related Post</h2>
            </div>
        </div>
        <div class="row">
            {% for post in posts %}
            <div class="col-md-6 col-lg-4">
                <a href="#" class="a-block d-flex align-items-center height-md"
                   style="background-image: url({{ post.image.url }}); ">
                    <div class="text">
                        <div class="post-meta">
                            <span class="category">{{ post.category }}</span>
                            <span class="mr-2">{{ post.created_at }}</span> &bullet;
                            <span class="ml-2"><span class="fa fa-comments"></span> {{ comments.count }}</span>
                        </div>
                        <h3>{{ post.title }}</h3>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/blog.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
<script nonce="b38160dd-4e40-47c4-be8c-7f1bbbc6c98c">try{(function(w,d){!function(j,k,l,m){j[l]=j[l]||{};j[l].executed=[];j.zaraz={deferred:[],listeners:[]};j.zaraz.q=[];j.zaraz._f=function(n){return async function(){var o=Array.prototype.slice.call(arguments);j.zaraz.q.push({m:n,a:o})}};for(const p of["track","set","debug"])j.zaraz[p]=j.zaraz._f(p);j.zaraz.init=()=>{var q=k.getElementsByTagName(m)[0],r=k.createElement(m),s=k.getElementsByTagName("title")[0];s&&(j[l].t=k.getElementsByTagName("title")[0].text);j[l].x=Math.random();j[l].w=j.screen.width;j[l].h=j.screen.height;j[l].j=j.innerHeight;j[l].e=j.innerWidth;j[l].l=j.location.href;j[l].r=k.referrer;j[l].k=j.screen.colorDepth;j[l].n=k.characterSet;j[l].o=(new Date).getTimezoneOffset();if(j.dataLayer)for(const w of Object.entries(Object.entries(dataLayer).reduce(((x,y)=>({...x[1],...y[1]})),{})))zaraz.set(w[0],w[1],{scope:"page"});j[l].q=[];for(;j.zaraz.q.length;){const z=j.zaraz.q.shift();j[l].q.push(z)}r.defer=!0;for(const A of[localStorage,sessionStorage])Object.keys(A||{}).filter((C=>C.startsWith("_zaraz_"))).forEach((B=>{try{j[l]["z_"+B.slice(7)]=JSON.parse(A.getItem(B))}catch{j[l]["z_"+B.slice(7)]=A.getItem(B)}}));r.referrerPolicy="origin";r.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(j[l])));q.parentNode.insertBefore(r,q)};["complete","interactive"].includes(k.readyState)?zaraz.init():j.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document)}catch(e){throw fetch("/cdn-cgi/zaraz/t"),e;};</script></head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at preview.colorlib.com Port 443</address>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"858fe3ffcdf10974","b":1,"version":"2024.2.1","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
</body></html>

templates/category.html
{% extends 'layouts/base.html' %}

{% block content %}

<section class="site-section">
    <div class="container">
        <div class="row mb-4">
            <div class="col-md-6">
                <h2 class="mb-4">Category: {{ cat_name }}</h2>
            </div>
        </div>
        <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
                <div class="row mb-5 mt-5">
                    <div class="col-md-12">
                        {% for post in posts %}
                        <div class="post-entry-horzontal">
                            <a href="/blog/{{ post.id }}">
                                <div class="image element-animate" data-animate-effect="fadeIn"
                                     style="background-image: url({{ post.image.url }});"></div>
                                <span class="text">
<div class="post-meta">
<span class="category">{{ post.category }}</span>
<span class="mr-2">{{ post.created_at }}</span> &bullet;
<span class="ml-2"><span class="fa fa-comments"></span>{{ comments.count }}</span>
</div>
<h2>{{ post.title }}</h2>
</span>
                            </a>
                        </div>
                        {% endfor%}

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <nav aria-label="Page navigation" class="text-center">
                            <ul class="pagination">
                                <li class="page-item  active"><a class="page-link" href="#">Prev</a></li>
                                {% for i in posts.paginator.page_range %}
                                {% if post.number == i %}
                                <li class="page-item"><a class="active">{{ i }}</a></li>
                                {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                                {% endfor %}
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>



        </div>
    </div>
</section>
{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

<section class="site-section">
    <div class="container">
        <div class="row mb-4">
            <div class="col-md-6">
                <h1>Contact</h1>
            </div>
        </div>
        <div class="row blog-entries">
            <div class="col-md-12 col-lg-8 main-content">
                <form action="#" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4 form-group">
                            <label for="name">Name</label>
                            <input name="name" type="text" id="name" class="form-control ">
                        </div>
                        <div class="col-md-4 form-group">
                            <label for="phone">Phone</label>
                            <input name="phone" type="text" id="phone" class="form-control ">
                        </div>
                        <div class="col-md-4 form-group">
                            <label for="email">Email</label>
                            <input name="email" type="email" id="email" class="form-control ">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="message">Write Message</label>
                            <textarea name="message" id="message" class="form-control " cols="30" rows="8"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary">
                        </div>
                    </div>
                </form>
            </div>

            {% include 'layouts/author_page.html' %}

        </div>
    </div>
</section>
{% endblock %}

templates/layouts/author_page.html
{% load static %}
<div class="col-md-12 col-lg-4 sidebar">


                <div class="sidebar-box">
                    <div class="bio text-center">

                        <div class="bio-body">
                            <h2>Abdulaziz Miralim</h2>
                            <p>Hey, I'm Abdulaziz, currently a Computer Science (IT) student at Amity University. With a strong
foundation in backend development, I've spent the past 2 years honing my skills . In addition to my
academic pursuits, I've successfully completed three personal projects, showcasing my ability to bring
ideas to life. I bring both academic knowledge and hands-on experience to the table. I'm eager to
explore opportunities where I can apply my skills to contribute effectively to a dynamic team.</p>
                            <p><a href="#" class="btn btn-primary btn-sm">Read my bio</a></p>
                            <p class="social">
                                <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
                                <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
                                <a href="#" class="p-2"><span class="fa fa-instagram"></span></a>
                                <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="sidebar-box">
                    <h3 class="heading">Popular Posts</h3>
                    <div class="post-entry-sidebar">
                        <ul>
                            {% for post in posts %}
                            <li>
                                <a href>
                                    <img src="{{ post.image.url }}" alt="Image placeholder" class="mr-4">
                                    <div class="text">
                                        <h4>{{ post.title }}</h4>
                                        <div class="post-meta">
                                            <span class="mr-2">{{ post.created_at }}</span> &bullet;
                                            <span class="ml-2"><span class="fa fa-comments"></span>{{ comments.count }}</span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="sidebar-box">
                    <h3 class="heading">Categories</h3>
                    <ul class="categories">
                        {% for category in categories %}
                        <li><a href="#">{{ category.name }} <span>{{ category.post_set.count }}</span></a></li>
                        {% endfor %}
                    </ul>

                </div>

                <div class="sidebar-box">
                    <h3 class="heading">Tags</h3>
                    <ul class="tags">
                        {% for tag in tags %}
                        <li><a href="/tag/{{ tag.id }}">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>